name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/recomendador-backend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy recomendador-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/recomendador-backend \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
